services:
  db:
    image: postgres:16
    container_name: fig-postgres
    environment:
      POSTGRES_USER: figcafe
      POSTGRES_PASSWORD: figcafe123
      POSTGRES_DB: fig_cafe_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: seongjin9018/fig-cafe-be:latest
    container_name: fig-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: figcafe
      DB_PASSWORD: figcafe123
      DB_DATABASE: fig_cafe_db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
